### PR TITLE
Update pack.json

### PR DESCRIPTION
**Pull request by Neolel**
Added `setting-groups` and `profiles` for all NNEDI3 upscalers from 16 to 256 neurons. With `ssim-downscaler` for downscaling and `krig-bilateral` for chroma upscaling.

### CODE REVIEW

**Comment by iwalton3** [comment]
What would you say the reasonable options are? I can leave all of the options in the pack, but I'd only prefer to add menu entries for items that would be reasonable to use by default. (Currently my menu system doesn't handle scrolling...)

The nnedi hooks referenced are from here, right? https://github.com/bjin/mpv-prescalers/tree/master
I also need to bundle those.

**Comment by Neolel** [comment]
I'd say up to 64 is absolutely reasonable. Maybe 128 is okay too in some rare cases but 256 just seems to be placebo for me. I just added all for completeness. Maybe creating another menu entry / directory for Anime4K and NNEDI3 or all shaders with multiple options to select from would be a nice idea to keep it tidy, i.e. `Video Playback Profiles - Anime4K - all shaders` and `Video Playback Profiles - NNEDI3 - all shaders`.

**Comment by iwalton3** [comment]
I'll probably consider that in the future. For now I'll add 64 and 128 to the menu.

**Comment by iwalton3** [comment]
Looks good! Changes are integrated and working.

**Pull request merged**
